[build-system]
requires = ["maturin>=1.13,<2.0"]
build-backend = "maturin"

[project]
name = "juwunit"
description = "Small JUnit XML serialization/deserialization for Python"
authors = [{ name = "Astral Software Inc.", email = "hey@astral.sh" }]
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]
license = "MIT OR Apache-2.0"
license-files = ["LICENSE-APACHE", "LICENSE-MIT"]

[project.urls]
Repository = "https://github.com/astral-sh/juwunit"
Documentation = "https://docs.astral.sh/juwunit"
Releases = "https://github.com/astral-sh/juwunit/releases"

[dependency-groups]
dev = [
    "inline-snapshot>=0.32.7",
    "maturin>=1.13,<2.0",
    "pytest>=8.0",
    "ty>=0.0.35",
]

[tool.maturin]
python-source = "."
module-name = "juwunit._juwunit"

[tool.inline-snapshot]
format-command = "ruff format --stdin-filename {filename}"

[tool.ty.analysis]
allowed-unresolved-imports = ["juwunit._juwunit"]
